"""empty message

Revision ID: 963f7a8cc87f
Revises: 0302460a6f20
Create Date: 2020-05-05 12:47:31.927881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963f7a8cc87f'
down_revision = '0302460a6f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
